### ISSUE TITLE
Wild Bench is extremely slow due to judge

### ISSUE THREAD

**Issue by aashay-sarvam** [mlfoundations/evalchemy#25]
-> Currently wildbench seems to take a long time for evaluation, can we add a variable to add num_workers for openai calls?

Also need some caching on results, so that I can run different evaluators/multiple rounds of it.

**Comment by vutrung96** [comment]
@neginraoof @RyanMarten this seems like the perfect use case for curator: https://github.com/bespokelabsai/curator

**Comment by vutrung96** [comment]
@EtashGuha too
